# Generated by Django 2.0.9 on 2019-06-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter area of study', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swetheory.AreaOfInterest')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_construct', to='swetheory.Construct')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('scope', models.TextField()),
                ('evidence_type', models.CharField(blank=True, choices=[('p', 'Philosophical'), ('e', 'Empyrical')], default='p', max_length=1)),
                ('doi_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition', to='swetheory.AreaOfInterest')),
                ('cause', models.ManyToManyField(to='swetheory.Cause')),
                ('effect', models.ManyToManyField(to='swetheory.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='evidenceeffect',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swetheory.Proposition'),
        ),
        migrations.AddField(
            model_name='effect',
            name='observed_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_effect_value', to='swetheory.Value'),
        ),
        migrations.AddField(
            model_name='construct',
            name='values',
            field=models.ManyToManyField(to='swetheory.Value'),
        ),
        migrations.AddField(
            model_name='cause',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cause_construct', to='swetheory.Construct'),
        ),
        migrations.AddField(
            model_name='cause',
            name='observed_value',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='observed_value', to='swetheory.Value'),
        ),
        migrations.AddField(
            model_name='cause',
            name='reference_value',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reference_value', to='swetheory.Value'),
        ),
    ]
