# Generated by Django 2.0.9 on 2019-06-25 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter area of study', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter construct name', max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construct', to='swetheory.AreaOfInterest')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect', to='swetheory.Construct')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('scope', models.TextField()),
                ('doi_number', models.IntegerField()),
                ('evidence_type', models.CharField(blank=True, choices=[('p', 'Philosophical'), ('e', 'Empyrical')], default='p', max_length=1)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='swetheory.AreaOfInterest')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition', to='swetheory.AreaOfInterest')),
                ('cause', models.ManyToManyField(to='swetheory.Cause')),
                ('effect', models.ManyToManyField(to='swetheory.Effect')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swetheory.EvidenceEffect')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter value', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='effect',
            name='observed_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_obs', to='swetheory.Value'),
        ),
        migrations.AddField(
            model_name='cause',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='swetheory.Construct'),
        ),
        migrations.AddField(
            model_name='cause',
            name='observed_value_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_obs', to='swetheory.Value'),
        ),
        migrations.AddField(
            model_name='cause',
            name='reference_value_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_ref', to='swetheory.Value'),
        ),
    ]
