# Generated by Django 2.0.9 on 2018-11-25 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swetheory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='cause_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='causeconstruct', to='swetheory.Construct'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='observed_cause_value',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='observedvalue', to='swetheory.Value'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='reference_cause_value',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='referencevalue', to='swetheory.Value'),
        ),
    ]
