# Generated by Django 2.0.9 on 2019-06-24 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swetheory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='name',
            new_name='cause',
        ),
        migrations.RenameField(
            model_name='cause',
            old_name='observed_value',
            new_name='observed_value_c',
        ),
        migrations.RenameField(
            model_name='cause',
            old_name='reference_value',
            new_name='reference_value_c',
        ),
        migrations.RenameField(
            model_name='effect',
            old_name='name',
            new_name='effect',
        ),
        migrations.AlterField(
            model_name='effect',
            name='observed_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_obs', to='swetheory.Value'),
        ),
    ]
