# Generated by Django 2.0.9 on 2019-06-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swetheory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenceeffect',
            name='area',
        ),
    ]
