# Generated by Django 2.0.9 on 2019-06-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swetheory', '0002_auto_20190616_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='name',
            field=models.CharField(help_text='Enter value', max_length=60),
        ),
    ]
