# Generated by Django 2.0.9 on 2018-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swetheory', '0002_auto_20181125_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='construct_values',
            field=models.ManyToManyField(to='swetheory.Value'),
        ),
    ]
