# Generated by Django 2.0.9 on 2019-06-17 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swetheory', '0003_auto_20190616_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construct',
            name='values',
        ),
        migrations.AlterField(
            model_name='cause',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='swetheory.Construct'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='observed_value',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cause_obs', to='swetheory.Value'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='reference_value',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cause_ref', to='swetheory.Value'),
        ),
        migrations.AlterField(
            model_name='construct',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construct', to='swetheory.AreaOfInterest'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effec', to='swetheory.Construct'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='observed_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect', to='swetheory.Value'),
        ),
    ]
